name: Deploy LMS and Django Apps

on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3  # Change this to match your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace with the path to your requirements.txt file

      - name: Set environment variables
        run: |
          echo "SECRET_KEY=N1i2t3h4i5!" >> .env
          echo "DATABASE_URL=mongodb+srv://nithiee03:<password>@cluster0.bckqasn.mongodb.net/" >> .env

    #   - name: Run database migrations
    #     run: |
    #       cd lms  # Replace with the path to your Django project directory
    #       python manage.py migrate

      # - name: Collect static files
      #   run: |
      #     cd lms  # Replace with the path to your Django project directory
      #     python manage.py collectstatic --noinput

      - name: Deploy badges
        run: |
          cd lms/djangoapps/badges
          
      - name: Deploy branding
        run: |
          cd lms/djangoapps/branding

      - name: Deploy bulk_email
        run: |
          cd lms/djangoapps/bulk_email

      - name: Deploy bulk_enroll
        run: |
          cd lms/djangoapps/bulk_enroll

      - name: Deploy bulk_user_retirement
        run: |
          cd lms/djangoapps/bulk_user_retirement

      - name: Deploy ccx
        run: |
          cd lms/djangoapps/ccx

      - name: Deploy certificates
        run: |
          cd lms/djangoapps/certificates

      - name: Deploy course_api
        run: |
          cd lms/djangoapps/course_api